version: "3.8"

volumes:
  pg_data:
  vscode:

services:
  postgres:
    image: postgres:13.0
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      LANG: ${LANG}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: .
    environment:
      DB_HOST: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USER: ${POSTGRES_USER}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: 5432
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET: ${DJANGO_SECRET}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    command:
      - sh
      - -c
      - sleep infinity
    volumes:
      - .:/home/container/app
      - vscode:/home/container/.vscode-server/extenstions
    depends_on:
      - postgres
    ports:
      - 8000:8000
